* Keys
| a = b             | a is an alias of b                               |
| a -> b            | The definition (b) of rule a.                    |
| a -> b, c, ..., z | Or'd definitions. a -> b or a -> c or ... a -> z |
| e                 | Empty string.                                    |
| 'a'               | Explicit string.                                 |
| ID                | Identifier alpha [alphanumeric, underscore]      |

* Aliases
TYPE = ID

* Base
program -> expr_list

expr_list -> expr expr_list, e
expr -> lemma

param_list -> TYPE ID param_list, e
ID_list -> ID ID_list, e

* Lemma
lemma -> sig '->' prop_list defn
sig -> TYPE ID param_list
defn -> app, imp

app -> ID ID_list out_vars
out_vars -> '>' ID_list

* Propositions
prop_list -> prop prop_list, e
prop -> ID ':' defn

* Implication
imp -> ID '->' ID_list imp_tail
imp_tail -> '->' ID_list imp_tail, e

* Semantics
** Modules
*** import
 import [filename: ID] [optional alias: ID]
*** namespacing
Function names are preceded by the file, e.g 
hello.bv:
saystuff ->
  puts "test"

main.bv:
import hello
main ->
  hello.saystuff
** Native
definition for an external c function to be loaded
@ [sig]

** Types definitions
**** Basic Types
typedef [type name: ID] [: [derived types: ID_list]]
const ID [value]

**** Groups
group [group name: ID] [functions: ID_list]

** Concurrency
csp model
! : output
? : input - returns false if everything falls asleep
?? : nonblocking input
MAX_THREADS : constant # of cores

main ->
  a: ? scan
  b: ? send
  a /\ b

scan ->
  scanned : scan_db > changes
  sent: ! changes
  scanned -> sent -> scan
  
send ->
  get: ? changes
  sent: send_changes changes
  get -> sent -> send

* Additional checks
** Suger
_ = ID that is mutable that goes to nothing
** Always false functions
Functions that will always be false cause a compilation error, 
but a flag can turn off this error (for testing).
** Deadlock
Some deadlock can be prevented by the CSP style checks. 
If a function tries to recieve more than it can obtain, then it fails
* Examples
** Proposition
   my_prop: add 1 1 > result
** Lemma
   my_lemma ->
      a: connect "google.com"
      b: send_message "GET /"
      c: get_response
      d: and a b
      and c d
** Implication
   upload_fun ->
      a: connect_to_db
      b: add_cat_photos
      c: close_db
      d: a -> b, c
      and a d
* Preprocessor
** Comments
Anything following a single quote will be ignored until the end of a line.
Multiline comments are two single quotes and ended by two single quotes. These can be embedded, e.g:
''
abc
123
''
another multi line comment
abc
''
''

evaluates to nothing.
** 
